In [1]:
import numpy as np

In [6]:
x = np.random.randint(10, size=(4,3,10))
print(x)
print('\n')
y = np.arange(4)
print(y)
print('\n')
split = np.asarray(np.split(x,5,axis=2))
print(np.reshape(split, (20,3,2)))
y = np.tile(y, 5)
print(y)

[[[9 6 9 9 5 1 0 1 3 1]
  [8 9 4 6 5 5 2 2 5 0]
  [1 6 8 1 3 4 8 8 0 2]]

 [[3 5 1 5 1 0 3 0 7 3]
  [7 7 9 4 9 9 0 6 4 0]
  [6 6 9 5 8 8 7 7 3 4]]

 [[9 4 1 4 8 2 6 9 2 9]
  [4 7 8 3 1 3 1 1 4 9]
  [6 9 5 0 5 7 7 6 1 4]]

 [[5 9 0 0 7 1 0 4 8 5]
  [9 5 7 6 1 6 1 5 4 6]
  [7 8 9 0 4 9 3 9 0 9]]]


[0 1 2 3]


[[[9 6]
  [8 9]
  [1 6]]

 [[3 5]
  [7 7]
  [6 6]]

 [[9 4]
  [4 7]
  [6 9]]

 [[5 9]
  [9 5]
  [7 8]]

 [[9 9]
  [4 6]
  [8 1]]

 [[1 5]
  [9 4]
  [9 5]]

 [[1 4]
  [8 3]
  [5 0]]

 [[0 0]
  [7 6]
  [9 0]]

 [[5 1]
  [5 5]
  [3 4]]

 [[1 0]
  [9 9]
  [8 8]]

 [[8 2]
  [1 3]
  [5 7]]

 [[7 1]
  [1 6]
  [4 9]]

 [[0 1]
  [2 2]
  [8 8]]

 [[3 0]
  [0 6]
  [7 7]]

 [[6 9]
  [1 1]
  [7 6]]

 [[0 4]
  [1 5]
  [3 9]]

 [[3 1]
  [5 0]
  [0 2]]

 [[7 3]
  [4 0]
  [3 4]]

 [[2 9]
  [4 9]
  [1 4]]

 [[8 5]
  [4 6]
  [0 9]]]
[0 1 2 3 0 1 2 3 0 1 2 3 0 1 2 3 0 1 2 3]
